In [10]:
from pathlib import Path

folder = Path("../data/raw/keystroke")

for item in folder.iterdir():
    print(item)

..\data\raw\keystroke\100_.tie5Roanl_keystroke_aggregated.csv
..\data\raw\keystroke\100_.tie5Roanl_keystroke_raw.csv
..\data\raw\keystroke\100_.tie5Roanl_last_session_id.txt
..\data\raw\keystroke\101_.tie5Roanl_keystroke_aggregated.csv
..\data\raw\keystroke\101_.tie5Roanl_keystroke_raw.csv
..\data\raw\keystroke\101_.tie5Roanl_last_session_id.txt
..\data\raw\keystroke\102_.tie5Roanl_keystroke_aggregated.csv
..\data\raw\keystroke\102_.tie5Roanl_keystroke_raw.csv
..\data\raw\keystroke\102_.tie5Roanl_last_session_id.txt
..\data\raw\keystroke\103_.tie5Roanl_keystroke_raw.csv
..\data\raw\keystroke\103_.tie5Roanl_last_session_id.txt
..\data\raw\keystroke\104_.tie5Roanl_keystroke_aggregated.csv
..\data\raw\keystroke\104_.tie5Roanl_keystroke_raw.csv
..\data\raw\keystroke\104_.tie5Roanl_last_session_id.txt
..\data\raw\keystroke\105_.tie5Roanl_keystroke_aggregated.csv
..\data\raw\keystroke\105_.tie5Roanl_keystroke_raw.csv
..\data\raw\keystroke\105_.tie5Roanl_last_session_id.txt

In [11]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/keystroke/100_.tie5Roanl_keystroke_raw.csv"
)

print(df.shape)
df.head()

(2815, 10)

,User_ID,Session_ID,Key_Pressed,Key_Pressed_Previous,Press_Time,Release_Time,Hold_Time,DD,UD,Characters_Count
0,Filip24m,1,Key.enter,NaN,1.737325e+09,1.737325e+09,0.000000,NaN,NaN,1
1,Filip24m,1,.,Key.enter,1.737325e+09,1.737325e+09,0.101579,3.973848,NaN,2
2,Filip24m,1,t,.,1.737325e+09,1.737325e+09,0.183444,0.414986,0.313407,3
3,Filip24m,1,i,t,1.737325e+09,1.737325e+09,0.148910,0.185115,0.001671,4
4,Filip24m,1,e,i,1.737325e+09,1.737325e+09,0.149346,0.666813,0.517903,5

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2815 entries, 0 to 2814
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   User_ID               2815 non-null   object
 1   Session_ID            2815 non-null   int64
 2   Key_Pressed           2815 non-null   object
 3   Key_Pressed_Previous  2811 non-null   object
 4   Press_Time            2815 non-null   float64
 5   Release_Time          2815 non-null   float64
 6   Hold_Time             2815 non-null   float64
 7   DD                    2811 non-null   float64
 8   UD                    2561 non-null   float64
 9   Characters_Count      2815 non-null   int64
dtypes: float64(5), int64(2), object(3)
memory usage: 220.1+ KB

In [13]:
df.columns

Index(['User_ID', 'Session_ID', 'Key_Pressed', 'Key_Pressed_Previous',
       'Press_Time', 'Release_Time', 'Hold_Time', 'DD', 'UD',
       'Characters_Count'],
      dtype='object')

In [15]:
agg = pd.read_csv(
    "../data/raw/keystroke/100_.tie5Roanl_keystroke_aggregated.csv"
)

print(agg.shape)
agg.head()

(154, 34)

,subject,sessionIndex,rep,H.period,DD.period.t,UD.period.t,H.t,DD.t.i,UD.t.i,H.i,...,H.a,DD.a.n,UD.a.n,H.n,DD.n.l,UD.n.l,H.l,DD.l.Return,UD.l.Return,H.Return
0,100,1,1,0.1146,0.4761,-0.1294,0.1294,0.1120,-0.1072,0.1072,...,0.1194,0.1296,-0.1153,0.1153,0.2298,-0.1260,0.1260,0.4497,-0.1129,0.1129
1,100,1,2,0.1183,0.9845,-0.1405,0.1405,0.1345,-0.1071,0.1071,...,0.1471,0.1649,-0.0797,0.0797,0.7189,-0.1161,0.1161,0.3485,-0.1475,0.1475
2,100,1,3,0.0736,0.4167,-0.1496,0.1496,0.1657,-0.1378,0.1378,...,0.1585,0.1750,-0.1294,0.1294,0.2796,-0.1342,0.1342,0.3355,-0.1847,0.1847
3,100,1,4,0.1203,0.1888,-0.1599,0.1599,0.1848,-0.1206,0.1206,...,0.1385,0.1748,-0.1272,0.1272,0.3179,-0.1285,0.1285,0.3894,-0.1778,0.1778
4,100,2,1,0.1245,0.1881,-0.1506,0.1506,0.2254,-0.1165,0.1165,...,0.1475,0.1240,-0.1236,0.1236,0.2677,-0.1155,0.1155,0.2747,-0.1623,0.1623

sessionIndex
1    2550
2    2550
3    2550
4    2550
5    2550
6    2550
7    2550
8    2550
Name: count, dtype: int64

In [7]:
df["rep"].max()

50

In [8]:
df["subject"].value_counts().head()

subject
s002    400
s003    400
s004    400
s005    400
s007    400
Name: count, dtype: int64